### PR TITLE
LIbrary:add-remove using redux

### PR DESCRIPTION
**Pull request by Melaku05**
-Structure application files using a "feature folder" 
-added add, remove functionality using redux

### CODE REVIEW

**Review by Meltrust — CHANGES_REQUESTED** [review]
Hi @Melaku05,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- The app works well✔️ 

You can do it

## Required Changes ♻️

- [x] On your readme, kindly please add the section "license" according to the [Microverse readme template](https://github.com/microverseinc/readme-template).  The link featured in that section should point to a file at the root of your project (the license file).   Just copy it from the mentioned template:

image

That way, we will meet this requirement, and your project will be well documented 💪 


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Melaku05** [comment]
Thank you, I did that.

**Comment by prolajumokeoni** [comment]
Hi @Melaku05, when I click on the MIT link on your readme it shows a 404 error

**Review by andersonlebon — APPROVED** [review]
## Hi @Melaku05 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

nodding-yes

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Your README file is now professional :heavy_check_mark: 

## Optional suggestions
- [ ] Kindly Check the comments under the review._
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Pull request merged**
